version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build:
    docker:
      - image: node:16.13.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test

      - run: npm run build

      - run: npm install netlify-cli -g

      - run: netlify deploy --prod --dir=build

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
