export enum commentTypes {
  FETCH_QUESTION_COMMENTS_REQUEST = 'FETCH_QUESTION_COMMENTS_REQUEST',
  FETCH_QUESTION_COMMENTS_SUCCESS = 'FETCH_QUESTION_COMMENTS_SUCCESS',
  FETCH_QUESTION_COMMENTS_FAILURE = 'FETCH_QUESTION_COMMENTS_FAILURE',
  EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST',
  EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS',
  EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE'
}
