export enum commentTypes {
  FETCH_QUESTION_COMMENTS_REQUEST = 'FETCH_QUESTION_COMMENTS_REQUEST',
  FETCH_QUESTION_COMMENTS_SUCCESS = 'FETCH_QUESTION_COMMENTS_SUCCESS',
  FETCH_QUESTION_COMMENTS_FAILURE = 'FETCH_QUESTION_COMMENTS_FAILURE',
  EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST',
  EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS',
  EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE',
  DELETE_A_COMMENT_REQUEST = 'DELETE_A_COMMENT_REQUEST',
  DELETE_A_COMMENT_SUCCESS = 'DELETE_A_COMMENT_SUCCESS',
  DELETE_A_COMMENT_FAILURE = 'DELETE_A_COMMENT_FAILURE',
  ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST',
  ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'
}
