export enum commentTypes {
  FETCH_QUESTION_COMMENTS_REQUEST = 'FETCH_QUESTION_COMMENTS_REQUEST',
  FETCH_QUESTION_COMMENTS_SUCCESS = 'FETCH_QUESTION_COMMENTS_SUCCESS',
  FETCH_QUESTION_COMMENTS_FAILURE = 'FETCH_QUESTION_COMMENTS_FAILURE'
}
