export enum notificationTypes {
  CREATE_NOTIFICATION_SOCKET_REQUEST = 'CREATE_NOTIFICATION_SOCKET_REQUEST',
  CREATE_NOTIFICATION_SOCKET_SUCCESS = 'CREATE_NOTIFICATION_SOCKET_SUCCESS',
  CREATE_NOTIFICATION_SOCKET_FAILURE = 'CREATE_NOTIFICATION_SOCKET_FAILURE',
  DESTROY_NOTIFICATION_SOCKET = 'DESTROY_NOTIFICATION_SOCKET',
  SEND_NOTIFICATION_REQUEST = 'SEND_NOTIFICATION_REQUEST',
  SEND_NOTIFICATION_SUCCESS = 'SEND_NOTIFICATION_SUCCESS',
  SEND_NOTIFICATION_FAILURE = 'SEND_NOTIFICATION_FAILURE',
  FETCH_UNREAD_NOTIFICATIONS_REQUEST = 'FETCH_UNREAD_NOTIFICATIONS_REQUEST',
  FETCH_UNREAD_NOTIFICATIONS_SUCCESS = 'FETCH_UNREAD_NOTIFICATIONS_SUCCESS',
  FETCH_UNREAD_NOTIFICATIONS_FAILURE = 'FETCH_UNREAD_NOTIFICATIONS_FAILURE',
  EDIT_NOTIFICATION_REQUEST = 'EDIT_NOTIFICATION_REQUEST',
  EDIT_NOTIFICATION_SUCCESS = 'EDIT_NOTIFICATION_SUCCESS',
  EDIT_NOTIFICATION_FAILURE = 'EDIT_NOTIFICATION_FAILURE',
  RECEIVE_A_NOTIFICATION_REQUEST = 'RECEIVE_A_NOTIFICATION_REQUEST',
  RECEIVE_A_NOTIFICATION_SUCCESS = 'RECEIVE_A_NOTIFICATION_SUCCESS',
  RECEIVE_A_NOTIFICATION_FAILURE = 'RECEIVE_A_NOTIFICATION_FAILURE'
}
