export enum questionListTypes {
  FETCH_QUESTIONLIST_REQUEST = 'FETCH_QUESTIONLIST_REQUEST',
  FETCH_QUESTIONLIST_SUCCESS = 'FETCH_QUESTIONLIST_SUCCESS',
  FETCH_QUESTIONLIST_FAILURE = 'FETCH_QUESTIONLIST_FAILURE'
}
