export enum questionTypes {
  FETCH_QUESTIONLIST_REQUEST = 'FETCH_QUESTIONLIST_REQUEST',
  FETCH_QUESTIONLIST_SUCCESS = 'FETCH_QUESTIONLIST_SUCCESS',
  FETCH_QUESTIONLIST_FAILURE = 'FETCH_QUESTIONLIST_FAILURE',
  FETCH_QUESTIONDETAILS_REQUEST = 'FETCH_QUESTIONDETAILS_REQUEST',
  FETCH_QUESTIONDETAILS_SUCCESS = 'FETCH_QUESTIONDETAILS_SUCCESS',
  FETCH_QUESTIONDETAILS_FAILURE = 'FETCH_QUESTIONDETAILS_FAILURE',
  POST_QUESTION_REQUEST = 'POST_QUESTION_REQUEST',
  POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS',
  POST_QUESTION_FAILURE = 'POST_QUESTION_FAILURE'
}
