export enum userTypes {
  FETCH_USER_REQUEST_ID = 'FETCH_USER_REQUEST_ID',
  FETCH_USER_BY_EMAIL_AND_VALIDATE_REQUEST = 'FETCH_USER_BY_EMAIL_AND_VALIDATE_REQUEST',
  FETCH_USER_BY_EMAIL_AND_VALIDATE_SUCCESS = 'FETCH_USER_BY_EMAIL_AND_VALIDATE_SUCCESS',
  FETCH_USER_BY_EMAIL_AND_VALIDATE_FAILURE = 'FETCH_USER_BY_EMAIL_AND_VALIDATE_FAILURE',
  FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE = 'FETCH_USER_FAILURE',
  FETCH_USERLIST_REQUEST = 'FETCH_USERLIST_REQUEST',
  FETCH_USERLIST_SUCCESS = 'FETCH_USERLIST_SUCCESS',
  FETCH_USERLIST_FAILURE = 'FETCH_USERLIST_FAILURE'
}
